bullets/urls.py
from django.urls import path
from .views import base_views, board_views, comment_views
# url의 name 값이 다른 모듈과 겹치면 오류가 발생하기에 app_name 을 지정해서 bullets에서만 사용하도록 하자.
app_name = 'bullets'
urlpatterns = [
    path('', base_views.index, name='index'),
    path('<int:board_id>/', base_views.detail, name='detail'),
    path('board/write/', board_views.board_write, name='board_write'),
    path('board/modify/<int:board_id>/', board_views.board_modify, name='board_modify'),
    path('board/delete/<int:board_id>/', board_views.board_delete, name='board_delete'),
    path('board/vote/<int:board_id>/', board_views.board_vote, name='board_vote'),
    path('comment/write/<int:board_id>/', comment_views.comment_write, name='comment_write'),
    path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),
    path('comment/vote/<int:comment_id>/', comment_views.comment_vote, name='comment_vote'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

bullets/models.py
# DB사용
from django.db import models
# 회원DB
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='board_author')
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    voter = models.ManyToManyField(User, related_name='board_voter')    # 추천인 추가

    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_author')
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now_add=True)
    voter = models.ManyToManyField(User, related_name='comment_voter')    # 추천인 추가

    def __str__(self):
        return self.content

bullets/forms.py
from django import forms
from bullets.models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title' , 'content']
        labels = {
            'title' : '제목',
            'content' : '내용',
        }
'''
        # 코드로 스타일을 주는건 프로그래머와 디자이너의 역할분담이 모호해진다. 그냥 가능하단것만 보여줌
        widgets = {
            'title': forms.TextInput(attrs={'class' : 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows' : 10}),
        }
'''
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content' : '댓글내용',
        }

bullets/views/base_views.py
# 게시글이 많을때 페이지처리하기
# render : html 페이지 랜더링
# get_object_or_404 : 글이 있으면보여주고, 해당번호의 글이 없으면 404 페이지
# 내가 만든 Board 앱
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from ..models import Board


# 로그인필요한 함수를 실행안되고 로그인으로 넘어가도록 함
# 메시지 알람을 띄운다.

def index(request):
    page = request.GET.get('page', '1') # 페이지값을 가져오고 없을경우 기본값을 1로한다.
    kw = request.GET.get('kw', '')  # 검색어를 가져오고 없을경우 기본값을 ""로한다.
    board_list = Board.objects.order_by('-date_created')
    if kw:
        board_list = board_list.filter(
            Q(title__icontains=kw) |   # 글제목 검색
            Q(content__icontains=kw) |   # 글내용 검색
            Q(comment__content__icontains=kw) |   # 댓글 제목검색
            Q(author__username__icontains=kw) |   # 글쓴이 검색
            Q(comment__author__username__icontains=kw)   # 댓글쓴이 검색
        ).distinct()
    paginator = Paginator(board_list, 30)   # 페이지당 보여질 갯수 설정
    page_obj = paginator.get_page(page)
    context = {'board': page_obj, 'page': page, 'kw': kw}
    return render(request, 'bullets/board_list.html', context)
def detail(request, board_id):
    # data = Board.objects.get(id=board_id)
    board = get_object_or_404(Board, pk=board_id)
    context = {'board': board}
    return render(request, 'bullets/board_detail.html', context)

bullets/views/board_views.py
# render : html 페이지 랜더링
# get_object_or_404 : 글이 있으면보여주고, 해당번호의 글이 없으면 404 페이지
# redirect : 글쓰기시 글을 DB에 넣었으면 다시 글내용보기 화면으로 이동
# 메시지 알람을 띄운다.
from django.contrib import messages
# 게시글이 많을때 페이지처리하기
# 로그인필요한 함수를 실행안되고 로그인으로 넘어가도록 함
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
# timezone : 글수정시 수정일을 넣고싶을때 현재 시간을 가져옴. 사용안할때는 그냥 주석처리함.
from django.utils import timezone

# 폼 콘트롤을 위한 게시판 폼 로드
from ..forms import BoardForm
# 내가 만든 Board 앱
from ..models import Board


@login_required(login_url='common:login')
def board_write(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user # 현재 로그인 사용자 정보
            board.date_modified = timezone.now()
            board.save()
            return redirect('bullets:index')
    else:
        form = BoardForm()
    data = {'form': form}
    return render(request, 'bullets/board_write.html', data)
@login_required(login_url='common:login')
def board_modify(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('bullets:detail', board_id=board_id)
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.date_modified = timezone.now()
            board.save()
            return redirect('bullets:detail', board_id=board_id)
    else:
        form = BoardForm(instance=board)
    context = {'form': form}
    return render(request, 'bullets/board_write.html', context)
@login_required(login_url='common:login')
def board_delete(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('bullets:detail', board_id=board_id)
    board.delete()
    return redirect('bullets:index')
@login_required(login_url='common:login')
def board_vote(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user == board.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        board.voter.add(request.user)
    return redirect('bullets:detail', board_id=board_id)

bullets/views/comment_views.py
# render : html 페이지 랜더링
# get_object_or_404 : 글이 있으면보여주고, 해당번호의 글이 없으면 404 페이지
# redirect : 글쓰기시 글을 DB에 넣었으면 다시 글내용보기 화면으로 이동
# 메시지 알람을 띄운다.
from django.contrib import messages
# 게시글이 많을때 페이지처리하기
# 로그인필요한 함수를 실행안되고 로그인으로 넘어가도록 함
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
# timezone : 글수정시 수정일을 넣고싶을때 현재 시간을 가져옴. 사용안할때는 그냥 주석처리함.
from django.utils import timezone

# 폼 콘트롤을 위한 게시판 폼 로드
from ..forms import CommentForm
# 내가 만든 Board 앱
from ..models import Board, Comment


@login_required(login_url='common:login')
def comment_write(request, board_id):
    # bullets 댓글 등록하기
    board = get_object_or_404(Board, pk=board_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.board = board
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('bullets:detail', board_id=board_id), comment.id))
    else:
        form = CommentForm()
    context = {'board': board, 'form': form}
    return render(request, 'bullets/board_detail.html', context)
@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('bullets:detail', board_id=comment.board.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.date_modified = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('bullets:detail', board_id=comment.board.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form':form}
    return render(request, 'bullets/comment_modify.html', context)
@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다.')
    else:
        comment.delete()
    return redirect('bullets:detail', board_id=comment.board.id)
@login_required(login_url='common:login')
def comment_vote(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        messages.error(request, '본인댓글은 추천을 할 수 업습니다.')
    else:
        comment.voter.add(request.user)
    return redirect('{}#comment_{}'.format(resolve_url('bullets:detail', board_id=comment.board.id), comment.id))

templates/bullets/board_detail.html
{% extends 'base.html' %}
{% load bullets_filter %}
{% block content %}
<div class="container my=3">
    <!-- 게시글 보여주기 -->
    <h2>{{ board.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{board.content|mark}}</div>
            <div class="d-flex justify-content-end">
                {% if board.date_modified != board.date_created %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ board.date_modified }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ board.author }}</div>
                    <div>{{ board.date_created }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'bullets:board_vote' board.id %}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{board.voter.count}}</span>
                </a>
            {% if request.user == board.author %}
                <a href="{% url 'bullets:board_modify' board.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'bullets:board_delete' board.id  %}">삭제</a>

            {% endif %}
            </div>
        </div>
    </div>
    <!-- 코멘트 보여주기 -->
    <h5 class="border-bottom my-3 py-2">{{board.comment_set.count}}개의 답변이 있습니다.</h5>
    {% for comment in board.comment_set.all %}
    <a id="comment_{{ comment.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ comment.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if comment.date_modified != comment.date_created %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ comment.date_modified }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ comment.author }}</div>
                    <div>{{ comment.date_created }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'bullets:comment_vote' comment.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{comment.voter.count}}</span>
            </a>
            {% if request.user == comment.author %}
            <a href="{% url 'bullets:comment_modify' comment.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'bullets:comment_delete' comment.id  %}">삭제</a>
            {% endif %}
        </div>
        </div>
    </div>
    {% endfor %}
    <!-- 코멘트 쓰기폼 -->
    <form action="{% url 'bullets:comment_write' board.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="4"
            {% if not user.is_authenticated %}disabled{% endif %}></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("확인을 누르면 이글을 추천합니다.")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/bullets/board_list.html
{% extends 'base.html' %}
{% load bullets_filter %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'bullets:board_write' %}" class="btn btn-primary">글쓰기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="witdh:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if board %}
        {% for article in board %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ board.paginator.count|sub:board.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'bullets:detail' article.id %}">{{ article.title }}</a>
                {% if article.comment_set.count > 0 %}
                <span class="text-danger small mx-2">{{ article.comment_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ article.author }}</td>
            <td>{{ article.date_created }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">글이 하나도 없네??? </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board.paginator.page_range %}
            {% if page_number >= board.number|add:-5 and page_number <= board.number|add:5 %}
                {% if page_number == board.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
                {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/bullets/board_write.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="title" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/bullets/comment_modify.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">댓글수정</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}